### ISSUE TITLE
🔴 Apple Silicon Mac Build Error

### ISSUE THREAD

**Issue by Thomas-Harrell** [rust-av/ssimulacra2_bin#33]
- I first use `git clone https://github.com/rust-av/ssimulacra2_bin` to download the repository to my local machine.

- Then I install the dependencies using [Homebrew](https://brew.sh/): `brew install rust` and `brew install vapoursynth`.

- After that, I run `cargo build` to build the project.

- However, I encountered an error message indicating that vapoursynth could not be found, even though I have already installed it.

```
error: linking with `cc` failed: exit status: 1

note: ld: library not found for -lvapoursynth

clang: error: linker command failed with exit code 1 (use -v to see invocation)

error: could not compile `ssimulacra2_rs` (bin "ssimulacra2_rs") due to previous error
```

**Comment by FreezyLemon** [comment]
You could try explicitly setting `VAPOURSYNTH_LIB_DIR` to tell the compiler where to find the necessary libraries. If you do, set it to `<VS root dir>/sdk/lib64` (lib32 if compiling for 32-bit)
