### ISSUE TITLE
Question on inputs

### ISSUE THREAD

**Issue by mabushey** [rust-av/ssimulacra2_bin#34]
This is awesome, thank you. One of my applications is slightly different, I would like to compare two different sources and determine which is better.

```
target/debug/ssimulacra2_rs image ~/test/0001.png ~/test/0001_50.jpg
Score: 67.41938821
target/debug/ssimulacra2_rs image ~/test/0001_50.jpg ~/test/0001.png
Score: 67.77785910
```

Is there a way to determine which image is the better one? Right now it just assumes the first is. This may be out of scope for what this algo does. Thanks for the help!

**Comment by FreezyLemon** [comment]
This is not an intended use case of the metric, and I can't think of a simple trick to achieve what you want with the algorithm. Sorry.

Note that this is more or less a port of the [C implementation](https://github.com/cloudinary/ssimulacra2) of the SSIMULACRA2 metric. If you have questions related to the metric or the algorithm itself, it might make more sense to ask a question over there.

**Comment by mabushey** [comment]
Thank you for answering my question!

**Comment by shssoichiro** [comment]
To clarify a bit more, I don't think there's a good way to achieve this with any metric, without having some "original" to compare to. Video metrics are typically used to compute _loss_ when compressing a source. In the case of having two different sources, the only real way to determine the better one is with your eyes.
